apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamelobby
  namespace: game
  labels:
    app: gamelobby
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gamelobby
  template:
    metadata:
      labels:
        app: gamelobby
    spec:
      containers:
        - name: gamelobby
          image: gamelobby:dev
          imagePullPolicy: IfNotPresent   # چون ایمیج را به minikube لود کردیم
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: REDIS__CONNECTION
              value: redis:6379
---
apiVersion: v1
kind: Service
metadata:
  name: gamelobby
  namespace: game
  labels:
    app: gamelobby
spec:
  selector:
    app: gamelobby
  ports:
    - name: http
      port: 8080
      targetPort: 8080
